InternetProdavnica/ViewModels/CreateRoleViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace InternetProdavnica.ViewModels
{
    public class CreateRoleViewModel
    {
        [Required]
        [Display(Name = "Role")]
        public string RoleName { get; set; }
    }
}

InternetProdavnica/ViewModels/EditRoleViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace InternetProdavnica.ViewModels
{
    public class EditRoleViewModel
    {
        public EditRoleViewModel()
        {
            Users = new List<string>();
        }
        public string Id { get; set; }
        [Required(ErrorMessage = "Morate dati ime roli!")]
        public string RoleName { get; set; }

        public List<string> Users { get; set; }
    }
}

InternetProdavnica/Controllers/AdministrationController.cs
using InternetProdavnica.Data;
using InternetProdavnica.Models;
using InternetProdavnica.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace InternetProdavnica.Controllers
{
    [Authorize(Roles = "Administrator")]
    public class AdministrationController : Controller
    {
        private readonly RoleManager<IdentityRole> roleManager;
        private readonly UserManager<ApplicationUser> userManager;
        private readonly InternetProdavnicaContext _context;

        public AdministrationController(RoleManager<IdentityRole> roleManager, UserManager<ApplicationUser> userManager, InternetProdavnicaContext context)
        {
            _context = context;
            this.roleManager = roleManager;
            this.userManager = userManager;
        }

        public IActionResult AdminPanel()
        {
            ViewBag.allOrders = _context.Narudzbenicas.ToList().Count();
            ViewBag.allProducts = _context.Proizvods.Where(p => p.IsDeleted == false && p.Aktivan == true).Count();
            ViewBag.allUnapprovedOrders = _context.Narudzbenicas.Where(n => n.Odobrena == false).Count();
            ViewBag.allRegisteredUsers = _context.Users.ToList().Count();
            ViewBag.allApprovedOrders = _context.Narudzbenicas.Where(n => n.Odobrena == true).Count();
            ViewBag.allRoles = _context.Roles.ToList().Count();
            ViewBag.allBills = _context.Racuns.ToList().Count();
            return View();
        }

        [HttpGet]
        public IActionResult CreateRole()
        {
            return View();
        }

        [HttpGet]
        public IActionResult ListUsers()
        {
            var users = userManager.Users;
            return View(users);
        }

        [HttpPost]
        public async Task<IActionResult> CreateRole(CreateRoleViewModel model)
        {
            if (ModelState.IsValid)
            {
                // We just need to specify a unique role name to create a new role
                IdentityRole identityRole = new IdentityRole
                {
                    Name = model.RoleName
                };

                // Saves the role in the underlying AspNetRoles table
                IdentityResult result = await roleManager.CreateAsync(identityRole);

                if (result.Succeeded)
                {
                    return RedirectToAction("ListRoles", "Administration");
                }

                foreach (IdentityError error in result.Errors)
                {
                    ModelState.AddModelError("", error.Description);
                }
            }

            return View(model);
        }

        [HttpGet]
        public IActionResult ListRoles()
        {
            var roles = roleManager.Roles;
            return View(roles);
        }

        [HttpGet]
        public async Task<IActionResult> EditRole(string id)
        {
            var role = await roleManager.FindByIdAsync(id);
            if (role == null)
            {
                ViewBag.ErrorMessage = $"Role with Id = {id} cannot be found";
                return View("NotFound");
            }

            var model = new EditRoleViewModel
            {
                Id = role.Id,
                RoleName = role.Name,
            };

            foreach(var user in await userManager.Users.ToListAsync())
            {
                if(await userManager.IsInRoleAsync(user, role.Name))
                {
                    model.Users.Add(user.UserName);
                }
            }

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> EditRole(EditRoleViewModel model)
        {
            var role = await roleManager.FindByIdAsync(model.Id);
            if (role == null)
            {
                ViewBag.ErrorMessage = $"Role with Id = {model.Id} cannot be found";
                return View("NotFound");
            }
            else
            {
                role.Name = model.RoleName;
                var result = await roleManager.UpdateAsync(role);

                if (result.Succeeded)
                {
                    return RedirectToAction("ListRoles");
                }

                foreach(var error in result.Errors)
                {
                    ModelState.AddModelError("", error.Description);
                }
                return View(model);
            }
        }

        [HttpGet]
        public async Task<IActionResult> EditUsersInRole(string roleId)
        {
            ViewBag.roleId = roleId;

            var role = await roleManager.FindByIdAsync(roleId);

            if (role == null)
            {
                ViewBag.ErrorMessage = $"Role with Id = {roleId} cannot be found";
                return View("NotFound");
            }

            var model = new List<UserRoleViewModel>();

            foreach(var user in await userManager.Users.ToListAsync())
            {
                var userRoleViewModel = new UserRoleViewModel
                {
                    UserId = user.Id,
                    UserName = user.UserName
                };

                if(await userManager.IsInRoleAsync(user, role.Name))
                {
                    userRoleViewModel.IsSelected = true;
                }
                else
                {
                    userRoleViewModel.IsSelected = false;
                }

                model.Add(userRoleViewModel);
            }

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> EditUsersInRole(List<UserRoleViewModel> model, string roleId)
        {
            var role = await roleManager.FindByIdAsync(roleId);

            if (role == null)
            {
                ViewBag.ErrorMessage = $"Role with Id = {roleId} cannot be found";
                return View("NotFound");
            }

            for(int i = 0; i < model.Count; i++)
            {
                var user = await userManager.FindByIdAsync(model[i].UserId);
                IdentityResult result = null;

                if(model[i].IsSelected && !(await userManager.IsInRoleAsync(user, role.Name)))
                {
                    result = await userManager.AddToRoleAsync(user, role.Name);
                }
                else if (!model[i].IsSelected && await userManager.IsInRoleAsync(user, role.Name))
                {
                    result = await userManager.RemoveFromRoleAsync(user, role.Name);
                }
                else
                {
                    continue;
                }

                if(result.Succeeded)
                {
                    // Kad AddToRoleAsync ili RemoveFromRoleAsync uspesno izvrse svoju funkciju stavlja se u polje 'result' i posmatra se kao result = succeeded
                    // Zato se pitamo ako result is succeeded da li posle njega ima jos UserRoleViewModel-a u listi. Ako ima nastavi dalje sa dodavanjem/oduzimanjem rola
                    // ako ne redirektuj nas na EditRole akciju
                    if (i < (model.Count) - 1)
                        continue;
                    else
                        // Poslednji succeeded uspesno zavrsen redirectuj nas na akciju EditRole
                        return RedirectToAction("EditRole", new { Id = roleId });
                }
            }

            return RedirectToAction("EditRole", new { Id = roleId });
        }
    }
}

InternetProdavnica/Controllers/BillController.cs
using InternetProdavnica.Data;
using InternetProdavnica.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace InternetProdavnica.Controllers
{
    public class BillController : Controller
    {
        private readonly InternetProdavnicaContext _context;
        public BillController(InternetProdavnicaContext context)
        {
            _context = context;
        }

        public IActionResult AllBills()
        {
            List<Racun> allBills = _context.Racuns.Include(p=> p.NarudzbenicaIdfkNavigation).ToList();
            return View(allBills);
        }
    }
}

InternetProdavnica/Controllers/OrderController.cs
using InternetProdavnica.Data;
using InternetProdavnica.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Text;

namespace InternetProdavnica.Controllers
{
    public class OrderController : Controller
    {
        private readonly InternetProdavnicaContext _context;
        private readonly IEmailSender _emailSender;
        private readonly IHttpContextAccessor _httpContextAccessor;
        public OrderController(InternetProdavnicaContext context, IEmailSender emailSender, IHttpContextAccessor httpContextAccessor)
        {
            _context = context;
            _emailSender = emailSender;
            _httpContextAccessor = httpContextAccessor;
        }
        public IActionResult AllOrders()
        {
            List<Narudzbenica> allOrders = _context.Narudzbenicas.ToList();
            return View(allOrders);
        }
        public IActionResult ApprovedOrders()
        {
            List<Narudzbenica> approvedOrders = _context.Narudzbenicas.Where(p => p.Odobrena == true).ToList();
            return View(approvedOrders);
        }
        public IActionResult OrdersOnWaitList()
        {
            List<Narudzbenica> ordersOnWaitList = _context.Narudzbenicas.Where(p => p.Odobrena == false).ToList();
            return View(ordersOnWaitList);
        }

        public IActionResult AllOrderItems(int id)
        {
            List<StavkaNarudzbenice> orderItems = _context.StavkaNarudzbenices.Where(o => o.NarudzbenicaIdfk == id).ToList();
            Narudzbenica order = _context.Narudzbenicas.Where(o => o.NarudzbenicaId == id).FirstOrDefault();
            ViewBag.orderID = order.NarudzbenicaId;
            return View(orderItems);
        }

        #region Creating Order
        [HttpGet]
        public IActionResult CreateOrder()
        {
            Narudzbenica order = new Narudzbenica();
            return View(order);
        }
        [HttpPost]
        public IActionResult CreateOrder(Narudzbenica order, string email, string imeIPrezime, string adresaIsporuke, string grad, string postanskiBroj, string drzava, string telefon)
        {
            List<Korpa> cartList = _context.Korpas.Include(p => p.ProizvodIdfkNavigation).Where(p => p.Active == true).ToList();
            bool loggedIn = HttpContext.User.Identity.IsAuthenticated;
            // Nova narudzbenica ID 1
            // Za svaku korpu dodaj stavku naruzbenice na narudzbenicu sa ID 1
            double ukupnaVrednost = 0;
            if(cartList.Count > 0)
            {
                order.Datum = DateTime.Now;
                order.Odobrena = false;
                if (loggedIn == true)
                {
                    //Dodati ovde da se prenosi parametar za email ulogovanog korisnika
                    order.email = _httpContextAccessor.HttpContext.User.Identity.Name;
                    order.Korisnik = _httpContextAccessor.HttpContext.User.Identity.Name;
                }
                else
                {
                    order.email = email;
                    order.Korisnik = "UnregisteredUser";
                }
                order.ImeIprezime = imeIPrezime;
                order.AdresaIsporuke = adresaIsporuke;
                order.Grad = grad;
                order.PostanskiBroj = postanskiBroj;
                order.Drzava = drzava;
                order.Telefon = telefon;
                order.UkupnaVrednost = 0;
                order.Administrator = "undefined";

                _context.Add(order);
                _context.SaveChanges();

                foreach (Korpa cart in cartList)
                {
                    _context.Add(new StavkaNarudzbenice()
                    {
                        KorpaIdfk = cart.KorpaId,
                        NarudzbenicaIdfk = order.NarudzbenicaId,
                        UkupnaVrednostStavke = cart.UkupnaVrednost,
                        NazivProizvoda = cart.ProizvodIdfkNavigation.NazivProizvoda,
                        Kolicina = cart.Kolicina
                    });
                    ukupnaVrednost += cart.UkupnaVrednost;
                    order.UkupnaVrednost = ukupnaVrednost;
                    cart.Active = false;
                }
                TempData["AlertMessage"] = "Uspešno ste naručili proizvode! Bice Vam poslata potvrda i racun na Vas e-mail cim procesiramo Vasu narudzbenicu! ID narudzbenice:" + order.NarudzbenicaId;
            }
            else
            {
                return RedirectToAction("AllProductsInCart", "Cart", new { area = "" });
                TempData["AlertMessage"] = "Morate dodati barem jedan proizvod u korpu!";
            }

            _context.SaveChanges();
            return RedirectToAction("AllProductsInCart", "Cart", new { area = "" });
        }
        #endregion

        #region Creating bill
        [Authorize(Roles = "Administrator")]
        public IActionResult ApproveOrder(int id, Racun racun)
        {
            Narudzbenica order = _context.Narudzbenicas.Find(id);
            List<StavkaNarudzbenice> orderItems = _context.StavkaNarudzbenices.Where(p => p.NarudzbenicaIdfk == order.NarudzbenicaId).ToList();
            
            StringBuilder sb = new StringBuilder();
            foreach(var itemOrder in orderItems)
            {
                sb.Append(itemOrder.NazivProizvoda + "Kolicina: " + itemOrder.Kolicina + "\n");
            }

            if(order.Odobrena == false)
            {
                order.Odobrena = true;
                order.Administrator = _httpContextAccessor.HttpContext.User.Identity.Name;

                racun.DatumRacuna = DateTime.Now;
                racun.UkupnaVrednostRacuna = order.UkupnaVrednost;
                racun.Izdat = true;
                racun.NarudzbenicaIdfk = order.NarudzbenicaId;
                racun.StavkeRacuna = sb.ToString();
                _context.Add(racun);
                _context.SaveChanges();
                TempData["AlertMessage"] = "Uspešno ste potvrdili narudzbenicu!";

                var message = new Message(new string[] { order.email }, "Potvrdjena narudzbenica, izdat racun", $"Hvala Vam na porucivanju!\n Vas broj racuna je: {racun.RacunId}.\n Molimo sacuvajte broj racuna, u slucaju da zelite da reklamirate proizvod bice Vam potreban vas broj racuna. Hvala Vam na poverenju, vasa PC prodavnica Beograd! \nNaruceni proizvodi: \n{sb}\n Ukupno za naplatu: {order.UkupnaVrednost} RSD\n Detalji za isporuku -\n Ime i prezime: {order.ImeIprezime}\n Adresa: {order.AdresaIsporuke}\n Grad: {order.Grad}\n Postanski broj: {order.PostanskiBroj}\n Mobilni telefon: {order.Telefon}");
                _emailSender.SendEmail(message);
            }
            else
            {
                TempData["AlertMessage"] = "Narudzbenica je vec potvrdjena!";
            }
            return RedirectToAction("AllOrders");
        }
        #endregion
    }
}

InternetProdavnica/Views/Administration/AdminPanel.cshtml
<div class="d-flex justify-content-center" style="margin-bottom:10%;">
    <div class="container">
        <h1 class="d-flex justify-content-center" style="margin-bottom:5%">Admin panel</h1>
        <div class="row">
          <div class="col-md-6">
              <span>
                  <a class="mojLink" href="@Url.Action("AllOrders","Order")">
                      <span>
                        <div class="col-md-12 pocetnaStranaTabele">
                            <h1><i class="bi bi-truck d-flex justify-content-center"></i></h1><p class="d-flex justify-content-center">Sve narudzbenice:&nbsp;<b>@ViewBag.allOrders</b></p>
                        </div>
                      </span>
                  </a>
               </span>
          </div>
          <div class="col-md-6">
              <span>
                  <a class="mojLink" href="@Url.Action("OrdersOnWaitList","Order")">
                      <span>
                        <div class="col-md-12 pocetnaStranaTabele">
                            <h1><i class="bi bi-truck-flatbed d-flex justify-content-center"></i></h1><p class="d-flex justify-content-center">Nepotvrdjene porudzbenice:&nbsp;<b>@ViewBag.allUnapprovedOrders</b></p>
                        </div>
                      </span>
                  </a>
               </span>
          </div>

          <!-- Force next columns to break to new line at md breakpoint and up -->
          <div class="w-100 d-none d-md-block"></div>

          <div class="col-md-6">
              <span>
                  <a class="mojLink" href="@Url.Action("ApprovedOrders","Order")">
                      <span>
                        <div class="col-md-12 pocetnaStranaTabele">
                            <h1><i class="bi bi-bag-check d-flex justify-content-center"></i></h1><p class="d-flex justify-content-center">Potvrđene narudzbenice:&nbsp;<b>@ViewBag.allApprovedOrders</b></p>
                        </div>
                      </span>
                  </a>
               </span>
          </div>

          <div class="col-md-6">
              <span>
                  <a class="mojLink" href="@Url.Action("AddProduct","Product")">
                      <span>
                        <div class="col-md-12 pocetnaStranaTabele">
                            <h1><i class="bi bi-box-seam d-flex justify-content-center"></i></h1><p class="d-flex justify-content-center">Proizvodi:&nbsp;<b>@ViewBag.allProducts</b></p>
                        </div>
                      </span>
                  </a>
               </span>
          </div>
          <div class="col-md-6">
              <span>
                  <a class="mojLink" href="@Url.Action("ListUsers","Administration")">
                      <span>
                        <div class="col-md-12 pocetnaStranaTabele">
                            <h1><i class="bi bi-people d-flex justify-content-center"></i></h1><p class="d-flex justify-content-center">Registrovani korisnici:&nbsp;<b>@ViewBag.allRegisteredUsers</b></p>
                        </div>
                      </span>
                  </a>
               </span>
          </div>
          <div class="col-md-6">
              <span>
                  <a class="mojLink" href="@Url.Action("ListRoles","Administration")">
                      <span>
                        <div class="col-md-12 pocetnaStranaTabele">
                            <h1><i class="bi bi-people d-flex justify-content-center"></i></h1><p class="d-flex justify-content-center">Role u sistemu:&nbsp;<b>@ViewBag.allRoles</b></p>
                        </div>
                      </span>
                  </a>
               </span>
          </div>
          <div class="col-md-6">
              <span>
                  <a class="mojLink" href="@Url.Action("AllBills","Bill")">
                      <span>
                        <div class="col-md-12 pocetnaStranaTabele">
                            <h1><i class="bi bi-receipt d-flex justify-content-center"></i></h1><p class="d-flex justify-content-center">Svi izdati racuni:&nbsp;<b>@ViewBag.allBills</b></p>
                        </div>
                      </span>
                  </a>
               </span>
          </div>
          <div class="col-md-6">
              <span>
                  <a class="mojLink" href="@Url.Action("AllComplaints","Complaint")">
                      <span>
                        <div class="col-md-12 pocetnaStranaTabele">
                            <h1><i class="bi bi-x-octagon d-flex justify-content-center"></i></h1><p class="d-flex justify-content-center">Trazene reklamacije:&nbsp;<b>@ViewBag.allBills</b></p>
                        </div>
                      </span>
                  </a>
               </span>
          </div>
        </div>
    </div>
</div>

InternetProdavnica/Views/Administration/CreateRole.cshtml
@using InternetProdavnica.ViewModels
@model CreateRoleViewModel

@{
    ViewBag.Title = "Create New Role";
}

<form asp-action="CreateRole" method="post" class="mt-3">
    <div asp-validation-summary="All" class="text-danger">
    </div>
    <div class="form-group row">
        <label asp-for="RoleName" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <input asp-for="RoleName" class="form-control" placeholder="Name">
            <span asp-validation-for="RoleName" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group row">
        <div class="col-sm-10">
            <button type="submit" class="btn btn-primary" style="width:auto">
                Create Role
            </button>
        </div>
    </div>
</form>

InternetProdavnica/Views/Administration/EditRole.cshtml
@model InternetProdavnica.ViewModels.EditRoleViewModel

@{
    ViewBag.Title = "Edit Role";
}

<h1>Izmena role</h1>

<form method="post" class="mt-3">
    <div class="form-group row">
        <label asp-for="Id" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <input asp-for="Id" disabled class="form-control"/>
        </div>
    </div>
    <div class="form-group row">
        <label asp-for="RoleName" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <input asp-for="RoleName" class="form-control"/>
            <span asp-validation-for="RoleName" class="text-dangers"></span>
        </div>
    </div>

    <div asp-validation-summary="All" class="text-danger"></div>

    <div class="form-group row">
        <div class="col-sm-10">
            <button type="submit" class="btn btn-primary">Update</button>
            <a asp-action="ListRoles" class="btn btn-primary">Cancel</a>
        </div>
    </div>

    <div class="card">
        <div class="card-header">
            <h3>Korisnici u ovoj roli</h3>
        </div>
        <div class="card-body">
            @if(Model.Users.Any())
            {
                foreach(var user in Model.Users)
                {
                    <h5 class="card-title">@user</h5>
                }
            }
            else
            {
                <h5 class="card-title">Trenutno ni jedan korisnik nema ovu rolu</h5>
            }
        </div>
        <div class="card-footer"> 
            <a asp-action="EditUsersInRole" asp-controller="Administration" asp-route-roleId="@Model.Id" class="btn btn-primary" style="width:auto;">Add or remove users</a>
        </div>
    </div>
</form>

InternetProdavnica/Views/Administration/EditUsersInRole.cshtml
@model List<InternetProdavnica.ViewModels.UserRoleViewModel>

@{
    <!--Iz kontrolera prebacen roleId u view, ovako mozemo prebacivati podatke iz kontrolera u view!-->
    var roleId = ViewBag.roleId;
}

<form method="post">
    <div class="card">
        <div class="card-header">
            <h2>Dodaj ili ukloni korisnika iz ove role</h2>
        </div>
        <div class="card-body">
            @for (int i = 0; i< Model.Count; i++)
            {
                <div class="form-check m-1">
                    <input asp-for="@Model[i].IsSelected" class="form-check-input">
                    <input type="hidden" asp-for="@Model[i].UserId">
                    <input type="hidden" asp-for="@Model[i].UserName">
                    <label class="form-check-label" asp-for="@Model[i].IsSelected">
                        @Model[i].UserName
                    </label>
                </div>
            }
        </>
            <div class="card-footer">
                <input type="submit" value="Update" class="btn btn-primary" style="width:auto;"/>
                <a asp-action="EditRole" asp-route-id="@roleId" class="btn btn-primary" style="width:auto;">Cancel</a>
            </div>
        </div>
    </div>
</form>

InternetProdavnica/Views/Administration/ListRoles.cshtml
@model IEnumerable<IdentityRole>

@{
    ViewBag.Title = "All Roles";
}

<h1>Sve role u sistemu</h1>

@if(Model.Any())
{
    <a class="btn btn-primary mb-3" style="width:auto;" asp-action="CreateRole" asp-controller="Administration">
        Dodaj novu rolu
    </a>

    foreach(var role in Model)
    {
        <div class="card mb-3">
            <div class="card-header">
                Role Id : @role.Id
            </div>
            <div class="card-body">
                <h5 class="card-title">
                    @role.Name
                </h5>
            </div>
            <div class="card-footer">
                <a asp-action="EditRole" asp-controller="Administration" asp-route-id="@role.Id" class="btn btn-primary">Edituj</a>
                @*<a href="#" class="btn btn-danger">Obrisi</a>*@
            </div>
        </div>
    }
}
else
{
    <div class="card">
        <div class="card-header">
            Ni jedna rola nije kreirana
        </div>
        <div class="card-body">
            <h5 class="card-title">
                Iskoristi dugme ispod da napravis rolu
            </h5>
            <a class="btn btn-primary" style="width:auto;"
               asp-controller="Administration" asp-action="CreateRole">
                Napravi rolu
            </a>
        </div>
    </div>
}

InternetProdavnica/Views/Administration/ListUsers.cshtml
@model IEnumerable<ApplicationUser>

@{
    ViewBag.Title = "AllUsers";
}

<h1>Svi korisnici</h1>

@if (Model.Any())
{
    <a asp-action="Register" asp-controller="Account"
       class="btn btn-primary mb-3" style="width:auto">
        Dodaj novog korisnika
    </a>

    foreach (var user in Model)
    {
        <div class="card mb-3">
            <div class="card-header">
                User Id : @user.Id
            </div>
            <div class="card-body">
                <h5 class="card-title">@user.UserName</h5>
            </div>
            <div class="card-footer">
                @*<a href="#" class="btn btn-danger">Edit</a>
                <a href="#" class="btn btn-danger">Delete</a>*@
            </div>
        </div>
    }
}
else
{
    <div class="card">
        <div class="card-header">
            Jos uvek nema korisnika
        </div>
        <div class="card-body">
            <h5 class="card-title">
                Klikni na dugme ispod kako bi kreirao novog korisnika
            </h5>
            <a class="btn btn-primary" style="width:auto"
               asp-controller="Account" asp-action="Register">
                Add new user
            </a>
        </div>
    </div>
}