InternetProdavnica/Controllers/ComplaintController.cs
using InternetProdavnica.Data;
using InternetProdavnica.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace InternetProdavnica.Controllers
{
    public class ComplaintController : Controller
    {
        private readonly InternetProdavnicaContext _context;
        private readonly IEmailSender _emailSender;

        public ComplaintController(InternetProdavnicaContext context, IEmailSender emailSender)
        {
            _context = context;
            _emailSender = emailSender;
        }
        public IActionResult AllComplaints()
        {
            List<Reklamacija> allComplaints = _context.Reklamacijas.Include(p => p.RacunIdfkNavigation).Include(p=>p.RacunIdfkNavigation.NarudzbenicaIdfkNavigation).ToList();
            return View(allComplaints);
        }
        [HttpGet]
        public IActionResult AddComplaint()
        {
            Reklamacija reklamacija = new Reklamacija();
            return View(reklamacija);
        }

        [HttpPost]
        public IActionResult AddComplaint(Reklamacija reklamacija, int RacunID, string OpisReklamacije)
        {
            var id = from r in _context.Racuns
                     where r.RacunId == RacunID
                     select r;
            if(id.Any())
            {
                reklamacija.RacunIdfk = RacunID;
                reklamacija.OpisReklamacije = OpisReklamacije;
                reklamacija.Odobrena = false;
                _context.Add(reklamacija);
                _context.SaveChanges();
                TempData["AlertMessage"] = "Uspesno ste prijavili reklamaciju!";  
            }
            else
            {
                TempData["AlertMessage"] = "Ne postoji racun sa unetim brojem!";
            }
            return RedirectToAction("AddComplaint");
        }

        public IActionResult ApproveComplaint(int id)
        {
            Reklamacija complaint = _context.Reklamacijas.Include(p => p.RacunIdfkNavigation).Include(p => p.RacunIdfkNavigation.NarudzbenicaIdfkNavigation).Where(p => p.ReklamacijaId == id).First();
            if(complaint.Odobrena == false)
            {
                string email = complaint.RacunIdfkNavigation.NarudzbenicaIdfkNavigation.email;
                var message = new Message(new string[] { email }, "Reklamacija", $"Postovani {complaint.RacunIdfkNavigation.NarudzbenicaIdfkNavigation.ImeIprezime},\n Zelimo da Vas obavestimo da je vasa reklamacija vezana za broj racuna {complaint.RacunIdfk} odobrena! Bicete uskoro kontaktirani od strane naseg servisnog centra za dalja uputstva!\n Hvala Vam! Vasa PC Prodavnica Beograd.");
                _emailSender.SendEmail(message);
                complaint.Odobrena = true;
                _context.SaveChanges();
            }
            else
            {
                TempData["AlertMessage"] = "Reklamacija je vec potvrdjena!";
            }
            return View();
        }

        public IActionResult DisapproveComplaint(int id)
        {
            Reklamacija complaint = _context.Reklamacijas.Include(p => p.RacunIdfkNavigation).Include(p => p.RacunIdfkNavigation.NarudzbenicaIdfkNavigation).Where(p => p.ReklamacijaId == id).First();
            if (complaint.Odobrena == false)
            {
                string email = complaint.RacunIdfkNavigation.NarudzbenicaIdfkNavigation.email;
                var message = new Message(new string[] { email }, "Reklamacija", $"Postovani {complaint.RacunIdfkNavigation.NarudzbenicaIdfkNavigation.ImeIprezime},\n Zelimo da Vas obavestimo da je vasa reklamacija vezana za broj racuna {complaint.RacunIdfk} nazalost odbijena. Nazalost nismo mogli da nadjemo ni jedan los tehnicki detalj u vezi vasih kupljenih proizvoda!\n Hvala Vam! Vasa PC Prodavnica Beograd.");
                _emailSender.SendEmail(message);
                complaint.Odobrena = true;
                _context.SaveChanges();
            }
            else
            {
                TempData["AlertMessage"] = "Reklamacija je vec odbijena!";
            }
            return View();
        }
    }
}

InternetProdavnica/Views/Complaint/AddComplaint.cshtml
@model InternetProdavnica.Models.Reklamacija

@{
    ViewData["Title"] = "AddComplaint";
}

<h1 class="d-flex justify-content-center">Reklamacija</h1>

@if(@TempData["AlertMessage"] != null)
    {
        <div class="alert alert-success">
            @TempData["AlertMessage"]
        </div>
    }

<div class="row d-flex justify-content-center">
    <div class="col-md-4">
        <form asp-action="AddComplaint">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                Broj racuna
                <input type="text" name="RacunID" />
            </div>
            <div class="form-group">
                Opis reklamacije
                @*<input style="height:150px;" asp-for="OpisReklamacije" class="form-control" />*@
                <textarea class="complaintTextArea" rows="15" asp-for="OpisReklamacije"></textarea>
                <span asp-validation-for="OpisReklamacije" class="text-danger"></span><br />
            </div>
            <div class="form-group">
                <input type="submit" value="Posalji reklamaciju" class="siteButtonStyle" style="margin-left:30%;" />
            </div>
        </form>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

InternetProdavnica/Views/Complaint/AllComplaints.cshtml
@model IEnumerable<InternetProdavnica.Models.Reklamacija>

@{
    ViewData["Title"] = "AllComplaints";
}

<h1>Reklamacije</h1>

<table class="data">
    <thead style="border-bottom:1px solid black;">
        <tr>
            <th>
                Opis reklamacije
            </th>
            <th>
                ID racuna
            </th>
            <th>
                Ime lica koje je podnelo reklamaciju
            </th>
            <th>
                Kontakt telefon lica koje je podnelo reklamaciju
            </th>
            <th>
                E-mail lica koje je podnelo reklamaciju
            </th>
            <th>
                Odobrena reklamacija
            </th>
            <th>

            </th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr style="border-bottom:1px solid black;">
            <td>
                @Html.DisplayFor(modelItem => item.OpisReklamacije)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.RacunIdfkNavigation.RacunId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.RacunIdfkNavigation.NarudzbenicaIdfkNavigation.ImeIprezime)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.RacunIdfkNavigation.NarudzbenicaIdfkNavigation.Telefon)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.RacunIdfkNavigation.NarudzbenicaIdfkNavigation.email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Odobrena)
            </td>
            @if(item.Odobrena == true)
            {
                <td></td>
            }
            else
            {
                <td>
                    <form>
                        <input style="margin-bottom:5px;" type="submit" value="Odobri" asp-action="ApproveComplaint" asp-route-id="@item.ReklamacijaId" class="siteButtonStyle">
                    </form>
                    <form>
                        <input style="margin-bottom:5px;" type="submit" value="Odbij" asp-action="DisapproveComplaint" asp-route-id="@item.ReklamacijaId" class="siteButtonStyle">
                    </form>
                </td>
            }
        </tr>
}
    </tbody>
</table>

InternetProdavnica/Views/Complaint/ApproveComplaint.cshtml
@model InternetProdavnica.Models.Reklamacija

@{
    ViewData["Title"] = "ApproveComplaint";
}

<h1 class="d-flex justify-content-center" style="margin-top:30%;"> Uspesno ste odobrili reklamaciju!</h1>
<i class="bi bi-hand-thumbs-up d-flex justify-content-center" style="font-size:3em; margin-bottom:2%;"></i>
<a class="d-flex justify-content-center" style="margin-bottom:30%;" asp-action="AllComplaints" asp-controller="Complaint">Nazad</a>

InternetProdavnica/Views/Complaint/DisapproveComplaint.cshtml
@model InternetProdavnica.Models.Reklamacija

@{
    ViewData["Title"] = "DisapproveComplaint";
}

<h1 class="d-flex justify-content-center" style="margin-top:30%;"> Uspesno ste odbili reklamaciju!</h1>
<i class="bi bi-hand-thumbs-down d-flex justify-content-center" style="font-size:3em; margin-bottom:2%;"></i>
<a class="d-flex justify-content-center" style="margin-bottom:30%;" asp-action="AllComplaints" asp-controller="Complaint">Nazad</a>